### ISSUE TITLE
Training the model with new dataset

### ISSUE THREAD

**Issue by divakarsivashankar** [dalab/web2text#16]
Hi, 

I am trying to train the model with a different set of data. I am following through your steps.

I have 2 questions

1.  In the [Aligning cleaned text with original source](https://github.com/dalab/web2text#aligning-cleaned-text-with-original-source) should I be passing in the `source` as the HTML doc and the cleaned txt for `cleaned`
2. Is there a way to pick all the `html` files inside the input folder and dump them into one extract block and edge features csv file

**Comment by tvogels** [comment]
Hi!

1. Yes, that's correct.
2. This is possible, but will require a little work. I would start by copying `src/main/scala/ch/ethz/dalab/web2text/cleaneval/CleanEval.scala` and `src/main/scala/ch/ethz/dalab/web2text/cleaneval/Page.scala`, and adapting them to your own HTML files. You can then follow the instructions [here](https://github.com/dalab/web2text#extracting-features-for-cleaneval).

Hope this helps. Let me know if you get stuck somewhere!

**Comment by divakarsivashankar** [comment]
Hi @tvogels, 

Thanks for your quick response. 

It was helpful for me to get my data trained.

**Comment by divakarsivashankar** [comment]
Hi @tvogels,

I am trying to apply labels to some of the HTML files in the CleanEval test set for testing purpose. 

This is the command I run inside a Docker container.
```
sbt "runMain ch.ethz.dalab.web2text.ApplyLabelsToPage  /data/2.html /data/classified_result/2_classified_
labels /data/classified_result/2_applied_labels"                                               
```

I am getting the following exception.
""MalformedInputException" at this [line](https://github.com/dalab/web2text/blob/df1d343f8d9a1089aecc642bea8c3a466ee6aa4e/src/main/scala/ch/ethz/dalab/web2text/ApplyLabelsToPage.scala#L41)
```
[error] Exception in thread "main" java.nio.charset.MalformedInputException: Input length = 1          
[error]         at java.nio.charset.CoderResult.throwException(CoderResult.java:281)                   
[error]         at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)                           
[error]         at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)                               
[error]         at java.io.InputStreamReader.read(InputStreamReader.java:184)                          
[error]         at java.io.BufferedReader.fill(BufferedReader.java:161)                                
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:324)                            
[error]         at java.io.BufferedReader.readLine(BufferedReader.java:389)                            
[error]         at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:67)       
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:727)                         
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)                      
[error]         at scala.collection.TraversableOnce$class.addString(TraversableOnce.scala:320)         
[error]         at scala.collection.AbstractIterator.addString(Iterator.scala:1157)                    
[error]         at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:286)          
[error]         at scala.collection.AbstractIterator.mkString(Iterator.scala:1157)                     
[error]         at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:288)          
[error]         at scala.collection.AbstractIterator.mkString(Iterator.scala:1157)                     
[error]         at scala.collection.TraversableOnce$class.mkString(TraversableOnce.scala:290)          
[error]         at scala.collection.AbstractIterator.mkString(Iterator.scala:1157)                     
[error]         at ch.ethz.dalab.web2text.ApplyLabelsToPage$.applyLabelsToPage(ApplyLabelsToPage.scala:
41)                                                                                                    
[error]         at ch.ethz.dalab.web2text.ApplyLabelsToPage$.main(ApplyLabelsToPage.scala:28)          
[error]         at ch.ethz.dalab.web2text.ApplyLabelsToPage.main(ApplyLabelsToPage.scala)              
[error] Nonzero exit code returned from runner: 1                                                      
[error] (Compile / runMain) Nonzero exit code returned from runner: 1                                  
[error] Total time: 7 s, completed Apr 22, 2021 7:23:25 AM                                             
```

I get this exception only if I run the html files from the CleanEval dataset If I use a other random html pages I don't have this issue. 

Can you please help to resolve this.

**Comment by tvogels** [comment]
Hmm, that sounds like a problem with the file encoding. Is there any useful info on this page?
https://stackoverflow.com/questions/13327536/malformedinputexception-when-trying-to-read-entire-file
