### ISSUE TITLE
Not compatible with TF 2?

### ISSUE THREAD

**Issue by eahogue** [dalab/web2text#17]
`$ python src/main/python/main.py classify result/step_1_extracted_features result/step_2_classified_labels
2021-10-26 21:30:40.002411: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "src/main/python/main.py", line 7, in <module>
    from forward import EDGE_VARIABLES, UNARY_VARIABLES, edge, loss, unary
  File "/home/ubuntu/sandbox/alan134/web2text/src/main/python/forward.py", line 2, in <module>
    from tensorflow import variable_scope, convert_to_tensor
ImportError: cannot import name 'variable_scope' from 'tensorflow' (/home/ubuntu/anaconda3/envs/alan-env/lib/python3.8/site-packages/tensorflow/__init__.py)`

Looking up "variable_scope" I find this https://www.tensorflow.org/api_docs/python/tf/compat/v1/variable_scope.

It seems to be saying that this (and apparently a number of other methods) are deprecated and need to be replaced with something like `tf.compat.v1.variable_scope`.

I would do this myself but I am not well versed in TF. Any chance of getting this updated to work with TF2?

Thanks,
Alan

**Comment by tvogels** [comment]
Hi @eahogue , unfortunately, Tensorflow 2 changed significantly. Porting the code would be a bit of a challenge.

In a previous issue, we found that Tensorflow 1.15 works:
https://github.com/dalab/web2text/issues/14#issuecomment-751690982

Hope this is a bit useful. If you end up porting things to a more modern software stack, let us know, we would be delighted with any contributions.
