### ISSUE TITLE
Testing on other datasets (e.g. Dragnet)

### ISSUE THREAD

**Issue by mtlive** [dalab/web2text#5]
Is it possible to test your approach on newer datasets such as [Dragnet](https://github.com/seomoz/dragnet_data)? Cleaneval is really old and it doesn't reflect modern website designs.

**Comment by tvogels** [comment]
Hi @mtlive,
Sorry for the late response and thanks for the suggestion. I agree that it would be nice to have evaluations on Dragnet. If you happened to have done such an evaluation, I would be curious about the results.
