### ISSUE TITLE
Release "data/cleaneval.npy" for reproductibility

### ISSUE THREAD

**Issue by sally14** [dalab/web2text#7]
Hello, 

I am trying to benchmark some models against your train/test splits of the cleaneval data (thank you for releasing it as it is not available online anymore). 

However, you did not released your "data/cleaneval.npy" file, which is necessary to use your ```src/main/python/data.py``` script. 

The train/test splits are not replicable otherwise. 

Thank you in advance.

**Comment by tvogels** [comment]
Hi,

You should be able to generate this file following the instructions under [Extracting features for CleanEval](https://github.com/dalab/web2text/blob/master/README.md#extracting-features-for-cleaneval) and [Training the CNNs](https://github.com/dalab/web2text/blob/master/README.md#extracting-features-for-cleaneval).

Let me know if you need help with that.
